Deep learning via ANN

Importing librarires

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

Import dataset

In [3]:
dataset = pd.read_csv("/content/Dataset_master.xlsx - American Express User Exit Pred.csv")
x = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [5]:
print(y)

[0 0 0 ... 0 1 0]


Encoding categorial data

gender column: label encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:, 2] = label_encoder.fit_transform(x[:, 2])

geography column: onehot encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough' )
x = np.array(ct.fit_transform(x))

splitting data into training and testing sets

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 21)

Feature scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

ANN

Initializing

In [11]:
ann = tf.keras.models.Sequential()

adding input layers and hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

Adding output layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

ANN training

Compiling ANN

In [15]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training in training dataset

In [16]:
ann.fit(x_train, y_train, batch_size = 32, epochs=120)

Epoch 1/120
249/249 [==============================] - 1s 2ms/step - loss: 0.5728 - accuracy: 0.7683
Epoch 2/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4842 - accuracy: 0.7926
Epoch 3/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4635 - accuracy: 0.7926
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4547 - accuracy: 0.7954
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4487 - accuracy: 0.7966
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.7969
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4412 - accuracy: 0.7990
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4392 - accuracy: 0.8015
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.8029
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4355 - accura

Prediction

single prediction

In [17]:
print(ann.predict(sc.transform([[0.0, 0.1, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 159ms/step
[[False]]


prediction on dataset

In [18]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 1]
 [0 0]
 [0 0]]


Confusion matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1538   64]
 [ 222  162]]


0.8559919436052367