In [33]:
import numpy as np

In [34]:
demo = [10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [35]:
demo2 = [10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
x1 = np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [38]:
y = np.zeros(5, int)
y.dtype

dtype('int64')

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
x5 =np.ones(5)
x5[3] = 999
print(x5)

[  1.   1.   1. 999.   1.]


In [41]:
new_array = np.zeros((3,4,5))
print(new_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [42]:
new_array.shape

(3, 4, 5)

In [43]:
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
new_twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_twoD_array[1:3,0]

array([4, 7])

In [45]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x = x + 10
print(x)
print(x+y)

[11 12 13]
[15 17 19]


In [46]:
print(x*2)
print(x*y)

[22 24 26]
[44 60 78]


In [47]:
print(x.mean())
print(x.sum())

12.0
36


In [48]:
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])

val = ((p1-p2)**2)
print(val)



[9 9 9]
