Import libraries

In [1]:
import numpy as np
import pandas as pd

Import dataset

In [4]:
data_set = pd.read_csv("/content/Dataset_master.xlsx - Loan Distribution KNN Classific.csv")
# existing loans and credit score is given, and based on this decide the loan should be given or not

x = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [5]:
print(x)
print(y)

[[  0  84]
 [  0 100]
 [  0 100]
 [  0 106]
 [  0 112]
 [  0 112]
 [  0 112]
 [  0 117]
 [  0 117]
 [  0 123]
 [  0 123]
 [  0 123]
 [  0 128]
 [  0 128]
 [  0 128]
 [  0 145]
 [  0 145]
 [  0 150]
 [  0 156]
 [  0 156]
 [  0 167]
 [  0 178]
 [  0 178]
 [  0 178]
 [  0 184]
 [  0 184]
 [  0 189]
 [  0 195]
 [  0 200]
 [  0 200]
 [  0 212]
 [  0 217]
 [  0 217]
 [  0 217]
 [  0 228]
 [  0 234]
 [  0 234]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 245]
 [  0 262]
 [  0 262]
 [  0 262]
 [  0 267]
 [  0 278]
 [  0 278]
 [  0 278]
 [  0 284]
 [  0 284]
 [  0 289]
 [  0 289]
 [  0 289]
 [  0 295]
 [  0 300]
 [  0 300]
 [  0 306]
 [  0 306]
 [  0 306]
 [  0 317]
 [  0 317]
 [  0 323]
 [  0 323]
 [  0 323]
 [  0 328]
 [  0 334]
 [  0 334]
 [  0 334]
 [  0 334]
 [  1 339]
 [  0 339]
 [  1 345]
 [  0 350]
 [  1 350]
 [  0 362]
 [  0 362]
 [  0 362]
 [  1 362]
 [  1 367]
 [  0 378]
 [  0 389]
 [  0 389]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 400]
 [  0 400]

Splitting data in train and test set

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=21)

Feature scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
print(x_train)

[[-0.56962577 -1.47477748]
 [ 0.73473469  0.27870758]
 [-0.56962577  1.50096441]
 [ 2.03909516  1.19000154]
 [ 2.03909516  1.84215977]
 [ 2.03909516  1.8162462 ]
 [-0.56962577  0.27870758]
 [-0.56962577 -0.89604103]
 [-0.56962577 -1.25883105]
 [-0.56962577 -0.24820173]
 [-0.56962577 -0.34753709]
 [-0.56962577  0.08435579]
 [-0.56962577 -1.5222857 ]
 [-0.56962577 -0.13159065]
 [-0.56962577 -0.20069351]
 [ 2.03909516  1.47936976]
 [-0.56962577 -0.22660708]
 [ 2.03909516  1.8162462 ]
 [-0.56962577 -0.13159065]
 [ 0.73473469  1.28501797]
 [-0.56962577 -0.20069351]
 [-0.56962577 -0.46414816]
 [-0.56962577  0.99564975]
 [ 2.03909516  1.83352192]
 [-0.56962577 -1.66481035]
 [-0.56962577 -0.17909887]
 [-0.56962577 -1.04288461]
 [-0.56962577 -1.40135569]
 [ 2.03909516  1.21159618]
 [-0.56962577 -0.58507817]
 [-0.56962577 -0.10567708]
 [-0.56962577 -1.49637213]
 [ 2.03909516  1.71691084]
 [-0.56962577  0.54216223]
 [ 3.34345563  1.70827298]
 [ 0.73473469  1.42754262]
 [ 0.73473469  1.19000154]
 

In [27]:
print(x_test)

[[-0.56962577  0.46874044]
 [ 0.73473469  0.71060045]
 [ 0.73473469  0.11026936]
 [-0.56962577  0.83153045]
 [ 2.03909516  1.8162462 ]
 [ 0.73473469  0.15777757]
 [-0.56962577 -0.30002887]
 [ 0.73473469  1.40594797]
 [-0.56962577  1.52687798]
 [-0.56962577 -0.89604103]
 [ 0.73473469  1.19000154]
 [-0.56962577 -1.30633926]
 [ 2.03909516  1.62189441]
 [-0.56962577 -1.54388034]
 [ 3.34345563  1.82488406]
 [-0.56962577 -0.15318529]
 [ 2.03909516  1.6348512 ]
 [-0.56962577 -0.70600817]
 [-0.56962577 -1.49637213]
 [ 0.73473469 -0.46414816]
 [ 3.34345563  1.85943549]
 [ 0.73473469  0.131864  ]
 [-0.56962577  0.56375687]
 [-0.56962577 -0.2741153 ]
 [-0.56962577 -0.9953764 ]
 [-0.56962577 -0.58507817]
 [-0.56962577 -0.13159065]
 [ 0.73473469  1.60893762]
 [-0.56962577 -0.13159065]
 [ 0.73473469  1.16408797]
 [ 0.73473469  0.11026936]
 [-0.56962577 -1.37976105]
 [-0.56962577  0.131864  ]
 [-0.56962577  0.39963758]
 [-0.56962577 -0.9953764 ]
 [-0.56962577 -1.59570749]
 [ 0.73473469  1.09498511]
 

KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

Predicting

In [29]:
print(classifier.predict(sc.transform([[1,1000]])))

[1]


Predicting set results

In [30]:
y_pred = classifier.predict(x_test)

Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[37  3]
 [ 1 27]]


0.9411764705882353